#!/bin/bash
# Quick test commands for Vision Detector - Block 1

echo "============================================"
echo "Vision Detector - Quick Test Commands"
echo "============================================"
echo ""
echo "1. BUILD THE PACKAGE:"
echo "   cd ~/ros2_jazzy/vision-language-navigator"
echo "   colcon build --packages-select tb4_gz_rqt_launch"
echo "   source install/setup.bash"
echo ""
echo "2. LAUNCH SIMULATION (Terminal 1):"
echo "   ros2 launch turtlebot4_gz_bringup turtlebot4_gz.launch.py"
echo ""
echo "3. START VISION DETECTOR (Terminal 2):"
echo "   ros2 run tb4_gz_rqt_launch vision_detector_node"
echo ""
echo "4. VIEW DETECTIONS (Terminal 3):"
echo "   ros2 run rqt_image_view rqt_image_view /vision/detections"
echo ""
echo "5. SET TARGET OBJECT (Terminal 4):"
echo "   ros2 topic pub /detection_target std_msgs/String '{data: \"chair\"}' --once"
echo ""
echo "6. DRIVE ROBOT (Terminal 5 - optional):"
echo "   ros2 run teleop_twist_keyboard teleop_twist_keyboard"
echo ""
echo "============================================"
echo "ALTERNATIVE: Use test script"
echo "============================================"
echo "   ros2 run tb4_gz_rqt_launch test_vision_detector chair"
echo ""
echo "============================================"
echo "CHECK TOPICS:"
echo "============================================"
echo "   ros2 topic list | grep -E '(detection|image)'"
echo "   ros2 topic echo /detection_target"
echo ""
